name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Optional: Trigger on pull requests to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (if your app uses Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # Replace with your desired Node.js version

      # Install dependencies (if your app uses npm)
      - name: Install dependencies
        run: npm install

      # Build the application (if needed)
      #- name: Build application
       # run: npm run build

          # Download and install the Render CLI
      - name: Install Render CLI
        run: |
          # Download the Render CLI binary
          curl -o render-cli.zip -L https://github.com/renderinc/cli/releases/latest/download/render-cli-linux.zip

          # Unzip the binary
          unzip render-cli.zip -d render-cli

          # Make the binary executable
          chmod +x render-cli/render

          # Add the binary to the PATH
          echo "$(pwd)/render-cli" >> $GITHUB_PATH

          # Deploy using the Render CLI
          render deploy --api-key ${{ secrets.RENDER_API_KEY }} --service srv-cuq71e1opnds73eilqpg
