name: Deploy to Render

on:
  push:
    branches:
      - main  # Change to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      #- name: Build project (if applicable)
        #run: npm run build

      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/deploy/srv-{RENDER_SERVICE_ID}?key=${{ secrets.RENDER_API_KEY }}"
