name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # Adjust the Node.js version as per your project requirements

    - name: Install dependencies
      run: npm install

    #- name: Build app
      #run: npm run build # If your project requires building, e.g., if it uses TypeScript or has a build step

    - name: Zip the app
      run: |
        zip -r app.zip . -x ".git/*" ".github/*"

    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v1.0.0
      with:
        api-key: ${{ secrets.RENDER_API_KEY }}
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        zip: app.zip
